alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alFh --color'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias psto='ps aux|grep'
alias py='python3'
