PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -lFh --color=auto'
alias la='ls -AFh --color=auto'
alias l='ls -F --color=auto'
alias ls='ls -CF --color=auto'
alias psto='ps aux|grep'